language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
